[workspace]
members = [
    "kernel",
    "init",
    "klib",
    "syscall",
    "ipc",
    "malloc",
    "memintrinsics",
]
resolver = "2"

[profile.release]
opt-level = "s"
debug = 0
overflow-checks = false
lto = true
codegen-units = 1
panic = "abort"
