[package]
name = "malloc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
name = "malloc"

[features]
cramp32 = []

[dependencies]
klib = { path = "../klib" }
syscall = { path = "../syscall" }
ipc = { path = "../ipc" }
