[package]
name = "ipc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]
name = "ipc"

[features]
cramp32 = []

[dependencies]
klib = { path = "../klib" }
syscall = { path = "../syscall" }
